apiVersion: v1
kind: Service
metadata:
  name: embedding-worker-service
  labels:
    app: embedding-worker
spec:
  type: ClusterIP
  selector:
    app: embedding-worker
  ports:
    - name: http
      port: 8001
      targetPort: 8001