apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-services-deployment
  labels:
    app: ai-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-services
  template:
    metadata:
      labels:
        app: ai-services
    spec:
      containers:
        - name: ai-service
          image: sydai/ai_services:latest
          ports:
            - containerPort: 8000